<?php

// $Id$

/**
 * @file
 * Add county fields to Location address.
 */

/**
 * Implementation of hook_locationapi().
 */
function location_county_locationapi(&$location, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'fields':
      return array('county' => t('County'));

    case 'defaults':
      return array(
        'county' => array('default' => '', 'collect' => 0, 'weight' => 9),
      );

    case 'field_expand':
      if ($a3 == 'county') {
        return array(
          '#type' => 'textfield',
          '#title' => t('County'),
          '#size' => 20,
          '#maxlength' => 45,
          '#description' => NULL,
          '#required' => ($a4 == 2),
          '#default_value' => $location,
        );
      }
      break;

    case 'save':
      db_query('DELETE FROM {location_county} WHERE lid = %d', $location['lid']);
      if (!empty($location['county'])) {
        db_query("INSERT INTO {location_county} (lid, county) VALUES (%d, '%s')", $location['lid'], $location['county']);
      }
      break;

    case 'load':
      $fields = array('county' => '');
      if ($row = db_fetch_object(db_query('SELECT county FROM {location_county} WHERE lid = %d', $location['lid']))) {
        $fields['county'] = $row->county;
      }
      return $fields;

    case 'delete':
      db_query('DELETE FROM {location_county} WHERE lid = %d', $location['lid']);
      break;
  }
}

/**
 * Implementation of hook_views_api().
 */
function location_county_views_api() {
  return array(
    'api' => 2,
  );
}

/**
 * Implementation of hook_token_list().
 */
function location_county_token_list($type = 'all') {
  if ($type == 'node' || $type == 'user' || $type == 'all') {
    $tokens['location']['location-county_N'] = t('Location County (If there are multiple locations per node, N is the iteration, starting with 0)');
    return $tokens;
  }
}
